language: rust
rust:
  - 1.53.0
  - stable
  - beta
  - nightly
arch:
  - amd64
  - arm64

jobs:
  allow_failures:
    - rust: nightly

os: linux
dist: bionic
cache: cargo

before_script: |
  if [ "x$TRAVIS_RUST_VERSION" == xstable -a "x$TRAVIS_CPU_ARCH" == xamd64 ]; then
    cargo install cargo-tarpaulin
  fi

script:
- cargo clean
- cargo build
- cargo test

after_success: |
  if [ "x$TRAVIS_RUST_VERSION" == xstable -a "x$TRAVIS_CPU_ARCH" == xamd64 ]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
